---
- hosts: elasticsearch
  roles:
    - role: elasticsearch
  gather_facts: yes
  any_errors_fatal: true
  tags: [elasticsearch]

- hosts: kibana
  roles:
    - role: kibana
  gather_facts: yes
  any_errors_fatal: true
  tags: [kibana]     
  
   